import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Banner from "../components/Banner";
import Destinations from "../components/Destinations";
import styles from "../styles/Home.module.css";

export async function getServerSideProps() {
  // Call an external API endpoint to get tours.
  // You can use any data fetching library
  const res = await fetch("http://localhost:5000/api/v1/tours");
  const data = await res.json();
  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      tours:data.data,
    },
  };
}

export default function Home({tours}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Explore | Travel Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />
      <Destinations tours={tours} />
    </div>
  );
}
