import {
  faCalendar,
  faClock,
  faLocationDot,
  faStar,
  faCircleUp,
  faLaugh,
} from "@fortawesome/free-regular-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import moment from "moment";
import Head from "next/head";
import React from "react";
import style from "../../styles/Tour.module.css";

function SingleTour({ tour }) {
  console.log(tour);
  return (
    <>
      <Head>
        <title>Explore | {tour.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <section className={style.section_header}>
          <div className={style.header__hero}>
            <div className={style.header__hero_overlay}></div>
            <img
              className={style.header__hero_img}
              src="http://localhost:5000/img/tours/tour-1-cover.jpg"
            />
          </div>
          <div className={style.heading_box}>
            <h1 className={style.heading_primary}>
              <span>
                {tour.name}
              </span>
            </h1>
            <div className={"flex justify-around mt-[5rem]"}>
              <div className={"flex items-center text-white font-bold text-xl"}>
                <FontAwesomeIcon className={"mr-3"} icon={faLocationDot} />
                <FontAwesomeIcon icon="fa-regular fa-house" />
                <span className={style.heading_box__text}>
                  {tour.startLocation.description}{" "}
                </span>
              </div>
              <div className={"flex items-center text-white font-bold text-xl"}>
                <FontAwesomeIcon className={"mr-3"} icon={faClock} />

                <span className={style.heading_box__text}>
                  {tour.duration} days
                </span>
              </div>
            </div>
          </div>
          <div className="flex justify-between">
            <div className="bg-gray-100 w-1/2 px-[10rem] py-[3rem] ">
              <h1 className="text-green-400 font-bold text-xl ">
                QUICK FACTS
              </h1>
              <div className="flex items-center text-xl mt-3 ">
                <FontAwesomeIcon
                  icon={faCalendar}
                  className="text-green-400 mr-3 "
                />
                <span className="text-gray-400 uppercase text-center text-sm">
                  {moment(tour.startDates[0]).format("MMM yyyy")}
                </span>
              </div>
              <div className="flex items-center text-xl mt-3 ">
                <FontAwesomeIcon
                  icon={faCircleUp}
                  className="text-green-400 mr-3 "
                />
                <span className="text-gray-400 uppercase text-center text-sm">
                  {tour.difficulty}
                </span>
              </div>
              <div className="flex items-center text-xl mt-3 ">
                <FontAwesomeIcon
                  icon={faLaugh}
                  className="text-green-400 mr-3 "
                />
                <span className="text-gray-400 uppercase text-center text-sm">
                  {tour.maxGroupSize} members
                </span>
              </div>
              <div className="flex items-center text-xl mt-3 ">
                <FontAwesomeIcon
                  icon={faStar}
                  className="text-green-400 mr-3 "
                />
                <span className="text-gray-400 uppercase text-center text-sm">
                  {tour.ratingsAverage}
                </span>
              </div>
            </div>
            <div className="w-1/2 px-[10rem] py-[3rem] ">
              <h1 className="text-green-400 font-bold text-xl">
                ABOUT THE THE FOREST HIKER TOUR
              </h1>
              <p className="text-gray-400 mt-6 text-sm leading-[23px]">
                Ut enim ad minim veniam, quis nostrud exercitation ullamco
                laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
                dolor in reprehenderit in voluptate velit esse cillum dolore eu
                fugiat nulla pariatur. <br /> Lorem ipsum dolor sit amet,
                consectetur adipisicing elit, sed do eiusmod tempor incididunt
                ut labore et dolore magna aliqua. Excepteur sint occaecat
                cupidatat non proident, sunt in culpa qui officia deserunt
                mollit anim id est laborum.
              </p>
            </div>
          </div>
        </section>
      </div>
    </>
  );
}

export default SingleTour;
export async function getStaticProps(context) {
  console.log(context);
  // Call an external API endpoint to get tours.
  // You can use any data fetching library
  const res = await fetch(
    "http://localhost:5000/api/v1/tours?slug=" + context.params.slug
  );
  const data = await res.json();
  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      tour: data.data[0],
    },
  };
}
export async function getStaticPaths() {
  const res = await fetch("http://localhost:5000/api/v1/tours/");
  const data = await res.json();

  const paths = data.data.map((post) => ({ params: { slug: post.slug } }));
  return {
    paths,
    fallback: false,
  };
}
